databases:
  - name: budget_app_db
    databaseName: budget_app_db_p21w
    user: budget_app_db_p21w_user


services:
  - type: web
    name: Manuu
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_db_p21w
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false